/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */


STATIC_METADATA_BEGIN(1, COMMON_RAW)
//------------------------------------------------------------------------------
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_MAX_REGIONS)
        CONFIG_ENTRY_VALUE(1, MINT32);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_SENSITIVITY_RANGE)
        CONFIG_ENTRY_VALUE( 100, MINT32);
        CONFIG_ENTRY_VALUE( 200, MINT32);
        CONFIG_ENTRY_VALUE( 400, MINT32);
        CONFIG_ENTRY_VALUE( 800, MINT32);
        CONFIG_ENTRY_VALUE(1600, MINT32);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_EXPOSURE_TIME_RANGE)
        CONFIG_ENTRY_VALUE(       1000L, MINT64); //  1 us
        CONFIG_ENTRY_VALUE(30000000000L, MINT64); // 30 sec
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_MAX_FRAME_DURATION)
        CONFIG_ENTRY_VALUE(30000000000L, MINT64);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_ANTIBANDING_MODES)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_50HZ, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_60HZ, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_AUTO, MUINT8);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_MODES)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_AUTO_FLASH, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_ALWAYS_FLASH, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE, MUINT8);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES)
        CONFIG_ENTRY_VALUE( 5, MINT32);CONFIG_ENTRY_VALUE(30, MINT32);
        CONFIG_ENTRY_VALUE(15, MINT32);CONFIG_ENTRY_VALUE(15, MINT32);
        CONFIG_ENTRY_VALUE(30, MINT32);CONFIG_ENTRY_VALUE(30, MINT32);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_COMPENSATION_RANGE)
        CONFIG_ENTRY_VALUE(-3, MINT32);
        CONFIG_ENTRY_VALUE(+3, MINT32);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_COMPENSATION_STEP)
        CONFIG_ENTRY_VALUE(MRational(1, 1), MRational);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AF_AVAILABLE_MODES)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_AUTO, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_MACRO, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_CONTINUOUS_VIDEO, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE, MUINT8);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AWB_AVAILABLE_MODES)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_AUTO, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_INCANDESCENT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_FLUORESCENT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_WARM_FLUORESCENT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_DAYLIGHT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_CLOUDY_DAYLIGHT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_TWILIGHT, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_SHADE, MUINT8);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AVAILABLE_EFFECTS)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_MONO, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_NEGATIVE, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_SEPIA, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_WHITEBOARD, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_BLACKBOARD, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_AQUA, MUINT8);
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_AVAILABLE_SCENE_MODES)
        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_UNSUPPORTED, MUINT8);
#if 0
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_FACE_PRIORITY);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_ACTION);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_PORTRAIT);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_LANDSCAPE);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_NIGHT);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_THEATRE);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_BEACH);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_SNOW);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_SUNSET);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_STEADYPHOTO);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_FIREWORKS);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_SPORTS);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_PARTY);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_CANDLELIGHT);
//        CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_BARCODE);
#endif
    CONFIG_METADATA_END()
    //==========================================================================
    CONFIG_METADATA_BEGIN(MTK_CONTROL_SCENE_MODE_OVERRIDES)
        //  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_OFF, MUINT8);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_OFF, MUINT8);
#if 0
        //  MTK_CONTROL_SCENE_MODE_FACE_PRIORITY
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_OFF);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_OFF);
        CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_OFF);

        //  MTK_CONTROL_SCENE_MODE_ACTION
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_PORTRAIT
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_LANDSCAPE
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_NIGHT
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_THEATRE
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_BEACH
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_SNOW
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_SUNSET
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_STEADYPHOTO
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_FIREWORKS
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_SPORTS
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_PARTY
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_CANDLELIGHT
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

        //  MTK_CONTROL_SCENE_MODE_BARCODE
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);
        CONFIG_ENTRY_VALUE(XXX);

#endif
    CONFIG_METADATA_END()
    //==========================================================================
//------------------------------------------------------------------------------
STATIC_METADATA_END()


