/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */


{RIL_UNSOL_NEIGHBORING_CELL_INFO, responseStrings, WAKE_PARTIAL},   //0 in alps/hardware/ril/include/telephony/ril.h
{RIL_UNSOL_NETWORK_INFO, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_PHB_READY_NOTIFICATION,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SIM_INSERTED_STATUS,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_RADIO_TEMPORARILY_UNAVAILABLE, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_ME_SMS_STORAGE_FULL, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_SMS_READY_NOTIFICATION, responseVoid, WAKE_PARTIAL},     //10 in alps/hardware/ril/include/telephony/ril.h
{RIL_UNSOL_SCRI_RESULT, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SIM_MISSING,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_GPRS_DETACH, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_ATCI_RESPONSE, responseString, WAKE_PARTIAL},
{RIL_UNSOL_SIM_RECOVERY,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_VIRTUAL_SIM_ON,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_VIRTUAL_SIM_OFF,responseInts, WAKE_PARTIAL},
{RIL_UNSOL_INVALID_SIM, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_PS_NETWORK_STATE_CHANGED, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_ACMT, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_EF_CSP_PLMN_MODE_BIT, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_IMEI_LOCK, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_MMRR_STATUS_CHANGED, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SIM_PLUG_OUT, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_SIM_PLUG_IN, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_ETWS_NOTIFICATION, responseEtwsNotification, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_PLMN_CHANGED, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_REGISTRATION_SUSPENDED, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_STK_EVDL_CALL, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_DATA_PACKETS_FLUSH, responseInts, WAKE_PARTIAL},//Add for Modem indication of RB release.
{RIL_UNSOL_FEMTOCELL_INFO, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_STK_SETUP_MENU_RESET, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_APPLICATION_SESSION_ID_CHANGED, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_ECONF_SRVCC_INDICATION, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_IMS_ENABLE_DONE, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_IMS_DISABLE_DONE, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_IMS_REGISTRATION_INFO, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_ACTIVATED, responseSetupDedicateDataCall, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_MODIFIED, responseSetupDedicateDataCall, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_DEACTIVATED, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_RAC_UPDATE, responseVoid, WAKE_PARTIAL},//sm cause rac
{RIL_UNSOL_ECONF_RESULT_INDICATION, responseStrings, WAKE_PARTIAL},
//Remote SIM ME lock related APIs [Start]
{RIL_UNSOL_MELOCK_NOTIFICATION,responseInts, WAKE_PARTIAL},
//Remote SIM ME lock related APIs [End]
{RIL_UNSOL_CALL_FORWARDING, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_CRSS_NOTIFICATION,responseCrssN, WAKE_PARTIAL},
{RIL_UNSOL_INCOMING_CALL_INDICATION, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_CIPHER_INDICATION, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_CNAP,responseStrings, WAKE_PARTIAL}, //obsolete
{RIL_UNSOL_SIM_COMMON_SLOT_NO_CHANGED, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_DATA_ALLOWED, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_STK_CALL_CTRL, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_VOLTE_EPS_NETWORK_FEATURE_SUPPORT, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_CALL_INFO_INDICATION, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_VOLTE_EPS_NETWORK_FEATURE_INFO, responseEpcNetworkFeatureInfo, WAKE_PARTIAL},
{RIL_UNSOL_SRVCC_HANDOVER_INFO_INDICATION, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SPEECH_CODEC_INFO, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_MD_STATE_CHANGE, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_REMOVE_RESTRICT_EUTRAN, responseVoid, WAKE_PARTIAL},//CC33
{RIL_UNSOL_MO_DATA_BARRING_INFO, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SSAC_BARRING_INFO, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_SIP_CALL_PROGRESS_INDICATOR, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_ABNORMAL_EVENT, responseStrings, WAKE_PARTIAL},
/// M: CC071: Add Customer proprietary-IMS RIL interface. @{
{RIL_UNSOL_EMERGENCY_BEARER_SUPPORT_NOTIFY, responseInts, WAKE_PARTIAL},
/// @}
/// M: [C2K] MD IRAT feature. @{ 60
{RIL_UNSOL_INTER_3GPP_IRAT_STATE_CHANGE, responseIratStateChange, WAKE_PARTIAL},
/// @}
/// M: [C2K] AP IRAT feature. @{61
{RIL_UNSOL_LTE_BG_SEARCH_STATUS, responseInts, WAKE_PARTIAL},
/// @}
/// M: [C2K][IR][MD-IRAT] URC for GMSS RAT changed. @{ 62
{RIL_UNSOL_GMSS_RAT_CHANGED, responseInts, WAKE_PARTIAL},
/// M: [C2K][IR][MD-IRAT] URC for GMSS RAT changed. @}
{RIL_UNSOL_CDMA_CARD_TYPE, responseVoid, WAKE_PARTIAL},
//IMS
{RIL_UNSOL_IMS_ENABLE_START, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_IMS_DISABLE_START, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_IMSI_REFRESH_DONE, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_EUSIM_READY, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, responseString, WAKE_PARTIAL},
//WorldMode
{RIL_UNSOL_WORLD_MODE_CHANGED, responseInts, WAKE_PARTIAL},
/// M: for 3G VT only @{
{RIL_UNSOL_VT_STATUS_INFO, responseInts, WAKE_PARTIAL},
{RIL_UNSOL_VT_RING_INFO, responseVoid, WAKE_PARTIAL},
/// @}
//External SIM APIs [Start]
{RIL_UNSOL_VSIM_OPERATION_INDICATION, responseVsimOperationEvent, WAKE_PARTIAL},
//External SIM APIs [End]
//Reset Attach APN
{RIL_UNSOL_SET_ATTACH_APN, responseVoid, WAKE_PARTIAL},
/// M: MAL @{
{RIL_UNSOL_MAL_AT_INFO, responseRaw,WAKE_PARTIAL},
{RIL_UNSOL_MAIN_SIM_INFO, responseInts,WAKE_PARTIAL},
/// @}
{RIL_UNSOL_TRAY_PLUG_IN, responseVoid, WAKE_PARTIAL},
{RIL_UNSOL_CALLMOD_CHANGE_INDICATOR, responseStrings, WAKE_PARTIAL},
{RIL_UNSOL_VIDEO_CAPABILITY_INDICATOR, responseStrings, WAKE_PARTIAL},
// M: [LTE][Low Power][UL traffic shaping] Start
{RIL_UNSOL_LTE_ACCESS_STRATUM_STATE_CHANGE, responseInts, WAKE_PARTIAL},
// M: [LTE][Low Power][UL traffic shaping] End
// M: IMS/EPDG start
{RIL_UNSOL_SETUP_DATA_CALL_RESPONSE, responseUnsolSetupDataCall, WAKE_PARTIAL},
// M: IMS/EPDG end
