#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <sys/stat.h>
#include <utils/Log.h>
#include <unistd.h>

#ifdef __cplusplus
extern "C"
{
#endif

#include <Tfa9887.h>
#include <Tfa9887_Registers.h>
#include <assert.h>
#include <string.h>
#include <math.h>
#include <sys/stat.h>
#include <NXP_I2C.h>
#include <assert.h>
#include <string.h>
#include <math.h>
#include <Tfa98xx_internals.h>
#include <Tfa98xx_Registers.h>

#ifdef __cplusplus
}
#endif

#define LOG_TAG "TFA9887_INTERFACE"

static const unsigned int  TFA9887_I2C_ADDRESS  = 0x6E;
static const unsigned int TFA9887_SAMPLE_RATE  = 44100;
static int bypass_dsp = 0;//Bypass mode: 1;
static int mHandleintint = 0;

#define _fileno fileno

#define LOCATION_FILES "/etc/smartpa_params/"
#define PATCH_FILENAME "TFA9887_N1D2_2_4_1.patch"

/* the base speaker file, containing tCoef */
#define SPEAKER_FILENAME "KS_13X18_DUMBO_tCoef.speaker"
#define PRESET_FILENAME "HQ_KS_13X18_DUMBO.preset"
#define CONFIG_FILENAME "TFA9887_N1D2.config"
#define EQ_FILENAME "HQ_KS_13X18_DUMBO.eq"

static float tCoefFromSpeaker(Tfa98xx_SpeakerParameters_t speakerBytes)
{
    int iCoef;

    /* tCoef(A) is the last parameter of the speaker */
    iCoef = (speakerBytes[TFA9887_SPEAKERPARAMETER_LENGTH - 3] << 16) + (speakerBytes[TFA9887_SPEAKERPARAMETER_LENGTH - 2] << 8) + speakerBytes[
                TFA9887_SPEAKERPARAMETER_LENGTH - 1];

    return (float)iCoef / (1 << 23);
}

static void tCoefToSpeaker(Tfa98xx_SpeakerParameters_t speakerBytes, float tCoef)
{
    int iCoef;

    iCoef = (int)(tCoef * (1 << 23));

    speakerBytes[TFA9887_SPEAKERPARAMETER_LENGTH - 3] = (iCoef >> 16) & 0xFF;
    speakerBytes[TFA9887_SPEAKERPARAMETER_LENGTH - 2] = (iCoef >> 8) & 0xFF;
    speakerBytes[TFA9887_SPEAKERPARAMETER_LENGTH - 1] = (iCoef) & 0xFF;
}

static void muteAmplifier(Tfa9887_handle_t handle)
{
    Tfa9887_Error_t err;
    unsigned short status;
    int tries = 0;

    /* signal the TFA9887 to mute plop free and turn off the amplifier */
    err = Tfa9887_SetMute(handle, Tfa9887_Mute_Amplifier);
    assert(err == Tfa9887_Error_Ok);

    /* now wait for the amplifier to turn off */
    err = Tfa9887_ReadRegister16(handle, TFA9887_STATUSREG, &status);
    assert(err == Tfa9887_Error_Ok);
    while ((status & TFA9887_STATUS_SWS) == TFA9887_STATUS_SWS && (tries < 100) )
    {
        ALOGD("muteAmplifier read TFA9887_STATUSREG status = 0x%x ",status);
        usleep(10*1000);
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUSREG, &status);
        tries++;
        assert(err == Tfa9887_Error_Ok);
    }
}

static void loadSpeakerFile(const char *fileName, Tfa9887_SpeakerParameters_t speakerBytes)
{
    int ret;
    FILE *f;

    ALOGD("using speaker %s\n", fileName);

    f = fopen(fileName, "rb");
    assert(f != NULL);
    ret = fread(speakerBytes, 1, sizeof(Tfa9887_SpeakerParameters_t), f);
    assert(ret == sizeof(Tfa9887_SpeakerParameters_t));
    fclose(f);
    ALOGD("-using speaker %s\n", fileName);
}

/* load a speaker model from a file, as generated by the GUI, or saved from a previous execution */
static void setSpeaker(Tfa9887_handle_t handle, const char *fileName, Tfa9887_SpeakerParameters_t speakerBytes)
{
    Tfa9887_Error_t err;
    int ret;
    FILE *f;

    ALOGD("using speaker %s\n", fileName);

    f = fopen(fileName, "rb");
    assert(f != NULL);
    ret = fread(speakerBytes, 1, sizeof(Tfa9887_SpeakerParameters_t), f);
    assert(ret == sizeof(Tfa9887_SpeakerParameters_t));
    err = Tfa9887_DspWriteSpeakerParameters(handle, speakerBytes);
    assert(err == Tfa9887_Error_Ok);
    fclose(f);
}
/* save the current speaker model to a file, for future use */
static void saveSpeaker(Tfa9887_SpeakerParameters_t speakerBytes, const char *fileName)
{
    int ret;
    FILE *f;

    f = fopen(fileName, "wb");
    assert(f != NULL);
    ret = fwrite(speakerBytes, 1, sizeof(Tfa9887_SpeakerParameters_t), f);
    assert(ret == sizeof(Tfa9887_SpeakerParameters_t));
    fclose(f);
}

static void setConfig(Tfa9887_handle_t handle, const char *fileName)
{
    Tfa9887_Error_t err;
    Tfa9887_Config_t config;
    int ret;
    FILE *f;

    ALOGD("setConfig using config %s\n", fileName);


    f = fopen(fileName, "rb");
    assert(f != NULL);
    ret = fread(config, 1, sizeof(config), f);
    assert(ret == TFA9887_CONFIG_LENGTH);
    err = Tfa9887_DspWriteConfig(handle, config);
    assert(err == Tfa9887_Error_Ok);
    fclose(f);
}

/* load a preset from a file, as generated by the GUI, can be done at runtime */
static void setPreset(Tfa9887_handle_t handle, const char *fileName)
{
    int ret;
    int presetSize;
    unsigned char *buffer;
    FILE *f;
    struct stat st;
    Tfa9887_Error_t err;

    ALOGD("setPreset using preset %s\n", fileName);

    f = fopen(fileName, "rb");
    assert(f != NULL);
    ret = fstat(_fileno(f), &st);
    assert(ret == 0);
    presetSize = st.st_size;
    assert(presetSize == TFA9887_PRESET_LENGTH);
    buffer = (unsigned char *)malloc(presetSize);
    assert(buffer != NULL);
    ret = fread(buffer, 1, presetSize, f);
    assert(ret == presetSize);
    err = Tfa9887_DspWritePreset(handle, buffer);
    assert(err == Tfa9887_Error_Ok);
    fclose(f);
    free(buffer);
    ALOGD("-setPreset using preset %s\n", fileName);
}

/* load a set of EQ settings from a file, as generated by the GUI, can be done at runtime */
static void setEQ(Tfa9887_handle_t handle, const char *fileName)
{
    int ret;
    FILE *f;
    Tfa9887_Error_t err;
    int ind; /* biquad index */
    float b0, b1, b2, a1, a2; /* the coefficients */
    int line = 1;
    char buffer[256];

    ALOGD("using EQ %s\n", fileName);

    f = fopen(fileName, "rb");
    assert(f != NULL);

    while (!feof(f))
    {
        if (NULL == fgets(buffer, sizeof(buffer) - 1, f))
        {
            break;
        }
        ret = sscanf(buffer, "%d %f %f %f %f %f", &ind, &b0, &b1, &b2, &a1, &a2);
        if (ret == 6)
        {
            if ((b0 != 1) || (b1 != 0) || (b2 != 0) || (a1 != 0) || (a2 != 0))
            {
                err = Tfa9887_DspBiquad_SetCoeff(handle, ind, b0, b1, b2, a1, a2);
                assert(err == Tfa9887_Error_Ok);
                ALOGD("Loaded biquad %d\n", ind);
            }
            else
            {
                err = Tfa9887_DspBiquad_Disable(handle, ind);
                assert(err == Tfa9887_Error_Ok);
                ALOGD("Disabled biquad %d\n", ind);
            }
        }
        else
        {
            ALOGD("error parsing file, line %d\n", line);
            //break;
        }
        line++;
    }
    ALOGD("-using EQ %s\n", fileName);
    fclose(f);
}

/* load a DSP ROM code patch from file */
static void dspPatch(Tfa9887_handle_t handle, const char *fileName)
{
    ALOGD("dspPatch fileName = %s", fileName);
    int ret;
    int fileSize;
    unsigned char *buffer;
    FILE *f;
    struct stat st;
    Tfa9887_Error_t err;

    f = fopen(fileName, "rb");
    assert(f != NULL);
    ret = fstat(_fileno(f), &st);
    assert(ret == 0);
    fileSize = st.st_size;
    buffer = (unsigned char *)malloc(fileSize);
    assert(buffer != NULL);
    ret = fread(buffer, 1, fileSize, f);
    assert(ret == fileSize);
    err = Tfa9887_DspPatch(handle, fileSize, buffer);
    assert(err == Tfa9887_Error_Ok);
    fclose(f);
    free(buffer);
}

static char *stateFlagsStr(int stateFlags)
{
    static char flags[10];

    flags[0] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_Activity)) ? 'A' : 'a';
    flags[1] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_S_Ctrl)) ? 'S' : 's';
    flags[2] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_Muted)) ? 'M' : 'm';
    flags[3] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_X_Ctrl)) ? 'X' : 'x';
    flags[4] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_T_Ctrl)) ? 'T' : 't';
    flags[5] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_NewModel)) ? 'L' : 'l';
    flags[6] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_VolumeRdy)) ? 'V' : 'v';
    flags[7] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_Damaged)) ? 'D' : 'd';
    flags[8] = (stateFlags & (0x1 << Tfa9887_SpeakerBoost_SignalClipping)) ? 'C' : 'c';

    flags[9] = 0;
    return flags;
}

static void dump_state_info(Tfa9887_SpeakerBoost_StateInfo_t *pState)
{
    ALOGD("state: flags %s, agcGain %2.1f\tlimGain %2.1f\tsMax %2.1f\tT %d\tX1 %2.1f\tX2 %2.1f\tRe %2.2f\n",
          stateFlagsStr(pState->statusFlag),
          pState->agcGain,
          pState->limGain,
          pState->sMax,
          pState->T,
          pState->X1,
          pState->X2,
          pState->Re);
}

static void load_all_settings(Tfa9887_handle_t handle, Tfa9887_SpeakerParameters_t speakerBytes, const char *configFile, const char *presetFile,
                              const char *eqFile)
{
    Tfa9887_Error_t err;
    ALOGD("+load_all_settings");
    /* load fullmodel */
    err = Tfa9887_DspWriteSpeakerParameters(handle, speakerBytes);
    assert(err == Tfa9887_Error_Ok);

    /* load the settings */
    setConfig(handle, configFile);
    /* load a preset */
    setPreset(handle, presetFile);
    /* load an EQ file */
    setEQ(handle, eqFile);
    ALOGD("-load_all_settings");
}

static void waitCalibration(Tfa98xx_handle_t handle, int *calibrateDone)
{
    Tfa9887_Error_t err;
    int tries = 0;
    unsigned short mtp;
#define WAIT_TRIES 1000

    err = (Tfa9887_Error_t)Tfa98xx_ReadRegister16(handle, TFA9887_MTP, &mtp);

    /* in case of calibrate once wait for MTPEX */
    if (mtp & TFA9887_MTP_MTPOTC)
    {
        while ((*calibrateDone == 0) && (tries < TFA98XX_API_WAITRESULT_NTRIES))
        {
            // TODO optimise with wait estimation
            err = Tfa9887_ReadRegister16(handle, TFA9887_MTP, &mtp);
            *calibrateDone = (mtp & TFA9887_MTP_MTPEX);  /* check MTP bit1 (MTPEX) */
            tries++;
            ALOGD("waitCalibration tries = %d", tries);
        }
    }
    else   /* poll xmem for calibrate always */
    {
        while ((*calibrateDone == 0) && (tries < WAIT_TRIES))
        {
            // TODO optimise with wait estimation
            err = Tfa9887_DspReadMem(handle, 231, 1, calibrateDone);
            tries++;
            ALOGD("Tfa9887_DspReadMem tries = %d", tries);
        }
        if (tries == WAIT_TRIES)
        {
            ALOGD("calibrateDone 231 timedout\n");
        }
    }

}

Tfa9887_Error_t calculateSpeakertCoefA(
    Tfa9887_handle_t handle,
    Tfa9887_SpeakerParameters_t loadedSpeaker)
{
    ALOGD("calculateSpeakertCoefA");
    Tfa9887_Error_t err;
    float re25, tCoefA, tCoef;
    int Tcal; /* temperature at which the calibration happened */
    int T0;
    int calibrateDone = 0;

    err = Tfa9887_DspGetCalibrationImpedance(handle, &re25);
    assert(err == Tfa9887_Error_Ok);
    assert(fabs(re25) < 0.1); /* no calibration done yet */

    tCoef = tCoefFromSpeaker(loadedSpeaker);

    /* use dummy tCoefA, also eases the calculations, because tCoefB=re25 */
    tCoefToSpeaker(loadedSpeaker, 0.0f);
    load_all_settings(handle, loadedSpeaker, LOCATION_FILES CONFIG_FILENAME, LOCATION_FILES PRESET_FILENAME, LOCATION_FILES EQ_FILENAME);

    /* start calibration and wait for result */
    err = Tfa9887_SetConfigured(handle);
    assert(err == Tfa9887_Error_Ok);

    waitCalibration(handle, &calibrateDone);
    if (calibrateDone)
    {
        Tfa9887_DspGetCalibrationImpedance(handle, &re25);
    }
    else
    {
        ALOGD("Calibration is not done");
        re25 = 0;
    }
    err = Tfa9887_DspReadMem(handle, 232, 1, &Tcal);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("Resistance of speaker is %2.2f ohm @ %d degrees\n", re25, Tcal);

    /* calculate the tCoefA */
    T0 = 25; /* definition of temperature for Re0 */
    tCoefA = tCoef * re25 / (tCoef * (Tcal - T0) + 1); /* TODO: need Rapp influence */
    ALOGD("Calculated tCoefA %1.5f\n", tCoefA);

    /* update the speaker model */
    tCoefToSpeaker(loadedSpeaker, tCoefA);

    /* !!! The value is only written to the speaker file “loadspeaker?located in the memory of
    * the host and not in the physical file itself.
    * The physical file will always contain tCoef. The host needs to save tCoefA in this “loadedSpeaker?as it is needed
    * after the next cold boot to write the tCoefA value into MTP !!! */
    ALOGD("-calculateSpeakertCoefA");
    return err;
}

static void resetMtpEx(Tfa9887_handle_t handle)
{
    ALOGD("+resetMtpEx");
    Tfa9887_Error_t err;
    unsigned short mtp;
    unsigned short status;

    /* reset MTPEX bit because calibration happened with wrong tCoefA */
    err = Tfa9887_ReadRegister16(handle, TFA9887_MTP, &mtp);
    assert(err == Tfa9887_Error_Ok);
    /* all settings loaded, signal the DSP to start calibration, only needed once after cold boot */

    /* reset MTPEX bit if needed */
    if ((mtp & TFA9887_MTP_MTPOTC) && (mtp & TFA9887_MTP_MTPEX))
    {
        err = Tfa9887_WriteRegister16(handle, 0x0B, 0x5A); /* unlock key2 */
        assert(err == Tfa9887_Error_Ok);

        err = Tfa9887_WriteRegister16(handle, TFA9887_MTP, 1); /* MTPOTC=1, MTPEX=0 */
        assert(err == Tfa9887_Error_Ok);
        err = Tfa9887_WriteRegister16(handle, 0x62, 1 << 11); /* CIMTP=1 */
        assert(err == Tfa9887_Error_Ok);
    }

    do
    {
        usleep(10 * 1000);
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
        assert(err == Tfa9887_Error_Ok);

    }
    while ((status & TFA9887_STATUS_MTPB) == TFA9887_STATUS_MTPB);
    assert((status & TFA9887_STATUS_MTPB) == 0);
    ALOGD("-resetMtpEx");
}

static void coldStartup(Tfa9887_handle_t handle, unsigned int  SampleRate)
{
    ALOGD("coldStartup");
    Tfa9887_Error_t err;
    unsigned short status = 0;
    unsigned short value = 0;
    int tries = 0;

    /* load the optimal TFA9887 in HW settings */
    err = Tfa9887_Init(handle);
    assert(err == Tfa9887_Error_Ok);

    err = Tfa9887_SetSampleRate(handle, SampleRate);
    assert(err == Tfa9887_Error_Ok);

//    if (bypass_dsp == 1)
    {
        MtkTfa98xxBypassOn();
    }

    err = Tfa9887_Powerdown(handle, 0);
    assert(err == Tfa9887_Error_Ok);

    ALOGD("Waiting for AMPS and CLKS to start up\n"); // TODO make a clock wait in runtime
    err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);

    while (((status & TFA9887_STATUS_CLKS) == 0) &&
           (tries < TFA98XX_API_WAITRESULT_NTRIES))
    {
        /* not ok yet */
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
        assert(err == Tfa9887_Error_Ok);
        tries++;
    }

    if (tries >= TFA98XX_API_WAITRESULT_NTRIES)
    {
        ALOGD("CLKS start up timed-out\n");
    }
    tries = 0;

    while (((status & TFA9887_STATUS_AMPS) == 0) &&
           (tries < TFA98XX_API_WAITRESULT_NTRIES))
    {
        /* not ok yet */
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
        assert(err == Tfa9887_Error_Ok);
        tries++;
    }

    if (tries >= TFA98XX_API_WAITRESULT_NTRIES)
    {
        ALOGD("AMPS start up timed-out\n");
    }
    tries = 0;
    ALOGD("Tfa9887_WriteRegister16 TFA9887_CF_CONTROLS");
    /* some other registers must be set for optimal amplifier behaviour */
    if (Tfa98xx_Error_Ok == err)
    {
        err = Tfa9887_WriteRegister16(handle, TFA9887_CF_CONTROLS, 0x01);
    }

    /* Setting Cool flux enable */
    if (bypass_dsp == 0)
    {
        err = Tfa9887_ReadRegister16(handle, TFA9887_SYS_CTRL, &value);
        assert(err == Tfa98xx_Error_Ok);
        value |= TFA9887_SYSTEM_CONTROL_CFE;/*(1<<2)*/
        err = Tfa9887_WriteRegister16(handle, TFA9887_SYS_CTRL, value);
        assert(err == Tfa98xx_Error_Ok);
    }

    err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
    assert(err == Tfa98xx_Error_Ok);

    while (((status & TFA9887_STATUS_AMPS) == 1) &&
           (tries < TFA98XX_API_WAITRESULT_NTRIES))
    {
        /* not ok yet */
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
        assert(err == Tfa98xx_Error_Ok);
        tries++;
    }
    tries = 0;

    /* Wait for Cool flux to be ready to be released */
    usleep(30 * 1000);
    ALOGD("dspPatch  LOCATION_FILES coldboot.patch");
    /* Load cold-boot patch for the first time cold start-up*/
    dspPatch(handle, LOCATION_FILES "coldboot.patch");

    err = Tfa9887_ReadRegister16(handle, TFA9887_STATUSREG, &status);

    if (!(status & TFA9887_STATUS_ACS))
    {
        ALOGD("Not Cold booted");
        return;  /* ensure cold booted */
    }

    /* Enabling the amplifier */
    value |= TFA9887_SYSTEM_CONTROL_AMPE; /*(1<<3)*/

    err = Tfa9887_WriteRegister16(handle, TFA9887_SYS_CTRL, value);

    ALOGD("dspPatch LOCATION_FILES");

    /* cold boot, need to load all parameters and patches */
    /* patch the ROM code */
    /* Tfa9887 does not have patch at this moment */
    dspPatch(handle, LOCATION_FILES PATCH_FILENAME);
    ALOGD(" - coldStartup");

}

static void setOtc(Tfa9887_handle_t handle, unsigned short otcOn)
{
    Tfa9887_Error_t err;
    unsigned short mtp;
    unsigned short status;
    int mtpChanged = 0;

    err = Tfa9887_ReadRegister16(handle, TFA9887_MTP, &mtp);
    assert(err == Tfa9887_Error_Ok);

    assert((otcOn == 0) || (otcOn == 1));

    /* set reset MTPEX bit if needed */
    if ((mtp & TFA9887_MTP_MTPOTC) != otcOn)
    {
        /* need to change the OTC bit, set MTPEX=0 in any case */
        err = Tfa9887_WriteRegister16(handle, 0x0B, 0x5A); /* unlock key2 */
        assert(err == Tfa9887_Error_Ok);

        err = Tfa9887_WriteRegister16(handle, TFA9887_MTP, otcOn); /* MTPOTC=otcOn, MTPEX=0 */
        assert(err == Tfa9887_Error_Ok);
        err = Tfa9887_WriteRegister16(handle, 0x62, 1 << 11); /* CIMTP=1 */
        assert(err == Tfa9887_Error_Ok);

        mtpChanged = 1;

    }
    //usleep(13*16); /* need to wait until all parameters are copied into MTP */
    do
    {
        usleep(10 * 1000);
        err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
        assert(err == Tfa9887_Error_Ok);

    }
    while ((status & TFA9887_STATUS_MTPB) == TFA9887_STATUS_MTPB);
    assert((status & TFA9887_STATUS_MTPB) == 0);
    if (mtpChanged)
    {
        /* ensure the DSP restarts after this to read out the new value */
        err = Tfa9887_WriteRegister16(handle, 0x70, 0x1); /* DSP reset */
        assert(err == Tfa9887_Error_Ok);
    }
}

static void statusCheck(Tfa98xx_handle_t handle)
{
    Tfa9887_Error_t err;
    unsigned short status;

    /* Check status from register 0*/
    err = Tfa9887_ReadRegister16(handle, TFA9887_STATUS, &status);
    if (status & TFA9887_STATUS_WDS)
    {
        ALOGD("DSP watchDog triggerd");
        return;
    }
}

static int checkMTPEX(Tfa9887_handle_t handle)
{
    unsigned short mtp;
    Tfa9887_Error_t err;
    err = Tfa9887_ReadRegister16(handle, TFA9887_MTP, &mtp);
    assert(err == Tfa9887_Error_Ok);

    if (mtp & (1 << 1))  /* check MTP bit1 (MTPEX) */
    {
        return 1;    /* MTPEX is 1, calibration is done */
    }
    else
    {
        return 0;    /* MTPEX is 0, calibration is not done yet */
    }
}

static Tfa9887_handle_t g_handle = 0;
static Tfa9887_Mute_t mute;
static Tfa9887_SpeakerParameters_t lsModel;
static Tfa9887_SpeakerBoost_StateInfo_t stateInfo;
static Tfa9887_SpeakerParameters_t loadedSpeaker;
static float re25;
static float tCoefA;
static unsigned int mSpeakerSampleRate = 44100;

int StartUpNxpSpeaker()
{

    ALOGD("StartUpNxpSpeaker");
    Tfa9887_Error_t err = Tfa9887_Error_Other;
    int i;
    unsigned short mtp;
    unsigned char slave_address;
    int calibrateDone = 0;

    /* create handle */
    /* try all possible addresses, stop at the first found */
    for (slave_address = 0x6c; slave_address <= 0x6E ; slave_address += 2)
    {
        ALOGD("Trying slave address 0x%x\n", slave_address);
        err = Tfa9887_Open(slave_address, &g_handle);
        ALOGD("Tfa9887_Open err  0x%x\n", err);
        if (err == Tfa9887_Error_Ok)
        {
            ALOGD("StartUpNxpSpeaker err == Tfa9887_Error_Ok");
            break;
        }
    }
    /* should have found a device */
    assert(err == Tfa9887_Error_Ok);

    /* When using "tCoefA patch" tCoefA, the loudspeaker model does not need to be saved into by the host anymore*/
    /* tCoefA will be saved into MTP automatically by CoolFlux */
    /* cold boot, need to load all parameters and patches */
    coldStartup(g_handle, mSpeakerSampleRate);

    /*Set to calibration once*/
    setOtc(g_handle, 1);

    err = Tfa9887_ReadRegister16(g_handle, TFA9887_MTP, &mtp);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("MTP = 0x%x\n", mtp);

    loadSpeakerFile(LOCATION_FILES SPEAKER_FILENAME, loadedSpeaker);
    Tfa9887_SelectAmplifierInput(g_handle, Tfa9887_AmpInputSel_I2SLeft);

    /* Check if MTPEX bit is set for calibration once mode
    /* Calibration always would always do the complete 2 step calibration*/
    if (checkMTPEX(g_handle) == 0)
    {
        ALOGD("checkMTPEX(handle) == 0");
        /* ensure no audio during special calibration */
        err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Digital);
        assert(err == Tfa9887_Error_Ok);

        ALOGD("still tCoef in speaker file, special calibration needed\n");
        err = calculateSpeakertCoefA(g_handle, loadedSpeaker);
        assert(err == Tfa9887_Error_Ok);

        resetMtpEx(g_handle);

        /* force recalibration now with correct tCoefA */
        ALOGD(" 1 muteAmplifier");
        muteAmplifier(g_handle); /* clean shutdown to avoid plop */
        ALOGD(" 2 coldStartup");
        coldStartup(g_handle, mSpeakerSampleRate);
        ALOGD("-checkMTPEX(handle) == 0");
    }
    else
    {
        ALOGD("DSP already calibrated. Calibration skipped and previous calibration results loaded from MTP.\n");
    }

    load_all_settings(g_handle, loadedSpeaker, LOCATION_FILES CONFIG_FILENAME, LOCATION_FILES PRESET_FILENAME, LOCATION_FILES EQ_FILENAME);

    /* do calibration (again), if needed */
    ALOGD("Tfa9887_SetConfigured ");
    err = Tfa9887_SetConfigured(g_handle);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("waitCalibration ");
    waitCalibration(g_handle, &calibrateDone);
    if (calibrateDone)
    {
        ALOGD("Tfa9887_DspGetCalibrationImpedance ");
        Tfa9887_DspGetCalibrationImpedance(g_handle, &re25);
    }
    else
    {
        ALOGD("Calibration is not done");
        re25 = 0;
    }
    ALOGD("Calibration value is %2.2f ohm\n", re25);

    /*Checking the current status for DSP status and DCPVP */
    ALOGD("statusCheck ");
    statusCheck(g_handle);

    ALOGD("Tfa9887_SetMute ");
    err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Digital);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("Tfa9887_GetMute ");
    err = Tfa9887_GetMute(g_handle, &mute);
    assert(err == Tfa9887_Error_Ok);

    assert(mute == Tfa9887_Mute_Digital);

    for (i = 5; i >= 0; i--)
    {
        ALOGD("Setting volume to %3.1f dB\n", -6.0f * i);
        err = Tfa9887_SetVolume(g_handle, -6.0f * i);
        assert(err == Tfa9887_Error_Ok);
        dump_state_info(&stateInfo);
        usleep(1 * 1000);
    }
    ALOGD("return");

    return 0;
}

void MtkTfa98xxBypassOn(void)
{
    Tfa98xx_Error_t err = Tfa98xx_Error_Other;
    unsigned short i2SRead = 0;
    unsigned short sysRead = 0;
    unsigned short sysCtrlRead = 0;

    err = Tfa98xx_ReadRegister16(g_handle, TFA98XX_I2S_CONTROL, &i2SRead);
    err = Tfa98xx_ReadRegister16(g_handle, TFA98XX_I2S_SEL, &sysRead);
    err = Tfa98xx_ReadRegister16(g_handle, TFA98XX_SYSTEM_CONTROL, &sysCtrlRead);

    ALOGD("MtkTfa98xxBypassOn bypass_dsp = %d", bypass_dsp);

    if (bypass_dsp)
    {
        i2SRead &= ~(TFA98XX_I2SREG_CHSA_MSK); /* Set CHSA to bypass DSP */
        sysRead &= ~(TFA98XX_I2S_SEL_REG_DCFG_MSK);/* Set DCDC compensation to off */
        sysRead |= TFA98XX_I2S_SEL_REG_SPKR_MSK; /* Set impedance as 8ohm */
        sysCtrlRead &= ~(TFA98XX_SYS_CTRL_DCA_MSK);/* Set DCDC to follower mode */
        sysCtrlRead &= ~(TFA98XX_SYS_CTRL_CFE_MSK);/* Disable coolflux */
    }
    else
    {
        i2SRead |= TFA98XX_I2SREG_CHSA_MSK; /* Set CHSA to bypass DSP */
        sysRead |= TFA98XX_I2S_SEL_REG_DCFG_MSK;/* Set DCDC compensation to off */
        sysRead &= ~(TFA98XX_I2S_SEL_REG_SPKR_MSK); /* Set impedance as 8ohm */
        sysCtrlRead |= TFA98XX_SYS_CTRL_DCA_MSK;/* Set DCDC to follower mode */
        sysCtrlRead |= TFA98XX_SYS_CTRL_CFE_MSK;/* Disable coolflux */
    }

    /* Set CHSA to bypass DSP */
    err = Tfa98xx_WriteRegister16(g_handle, TFA98XX_I2S_CONTROL, i2SRead);
    /* Set DCDC compensation to off and set impedance as 8ohm */
    err = Tfa98xx_WriteRegister16(g_handle, TFA98XX_I2S_SEL, sysRead);
    /* Set DCDC to follower mode and disable coolflux  */
    err = Tfa98xx_WriteRegister16(g_handle, TFA98XX_SYSTEM_CONTROL, sysCtrlRead);

    return err;

}

void MtkTfa98xxSpeakerOn(void)
{
    Tfa9887_Error_t err;

    if (g_handle == 0)
    {
        tfa9887_init();
    }

    ALOGE("+MtkTfa98xxSpeakerOn");
    err = Tfa9887_Powerdown(g_handle, 0);
    printf("MtkTfa98xxSpeakerOn Tfa9887_Powerdown return value is %d.\n", err);
    assert(err == Tfa9887_Error_Ok);

    usleep(30 * 1000);  // IPLL from I2S WS

    err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Off);
    printf("MtkTfa98xxSpeakerOn Tfa9887_SetMute return value is %d.\n", err);
    assert(err == Tfa9887_Error_Ok);

    int i = 0;
    for (i = 5; i >= 0; i--)
    {
        ALOGD("Setting volume to %3.1f dB\n", -6.0f * i);
        err = Tfa9887_SetVolume(g_handle, -6.0f * i);
        assert(err == Tfa9887_Error_Ok);
        dump_state_info(&stateInfo);
        usleep(30 * 1000);
    }

    ALOGE("-MtkTfa98xxSpeakerOn");
}

void MtkTfa98xxSpeakerOff(void)
{
    Tfa9887_Error_t err;

    ALOGE("+MtkTfa98xxSpeakerOff");

    err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Digital);
    printf("MtkTfa98xxSpeakerOff Tfa9887_SetMute return value is %d.\n", err);
    assert(err == Tfa9887_Error_Ok);

    err = Tfa9887_Powerdown(g_handle, 1);
    printf("MtkTfa98xxSpeakerOff Tfa9887_Powerdown return value is %d.\n", err);
    assert(err == Tfa9887_Error_Ok);

    usleep(30 * 1000);  // IPLL from I2S WS

    ALOGE("-MtkTfa98xxSpeakerOff");
}



int tfa9887_check_tfaopen(void)
{
    ALOGD("tfa9887_check_tfaopen");
    if (g_handle == 0)
    {
        return 0;
    }
    else
    {
        return 1;
    }
}

int  tfa9887_init(void)
{
    ALOGD("tfa9887_init");

    Tfa9887_Error_t err = Tfa9887_Error_Other;
    int i;
    unsigned short mtp;
    unsigned char slave_address;
    int calibrateDone = 0;
    if (g_handle == 0)
    {
        /* create handle */
        /* try all possible addresses, stop at the first found */
        for (slave_address = 0x6c; slave_address <= 0x6E ; slave_address += 2)
        {
            ALOGD("Trying slave address 0x%x\n", slave_address);
            err = Tfa9887_Open(slave_address, &g_handle);
            ALOGD("Tfa9887_Open err  0x%x\n", err);
            if (err == Tfa9887_Error_Ok)
            {
                ALOGD("StartUpNxpSpeaker err == Tfa9887_Error_Ok");
                break;
            }
        }
        /* should have found a device */
        assert(err == Tfa9887_Error_Ok);
    }

    /* create handle */
    /* try all possible addresses, stop at the first found */
    for (slave_address = 0x6c; slave_address <= 0x6E ; slave_address += 2)
    {
        ALOGD("Trying slave address 0x%x\n", slave_address);
        err = Tfa9887_Open(slave_address, &g_handle);
        ALOGD("Tfa9887_Open err  0x%x\n", err);
        if (err == Tfa9887_Error_Ok)
        {
            ALOGD("StartUpNxpSpeaker err == Tfa9887_Error_Ok");
            break;
        }
    }
    /* should have found a device */
    assert(err == Tfa9887_Error_Ok);

    /* When using "tCoefA patch" tCoefA, the loudspeaker model does not need to be saved into by the host anymore*/
    /* tCoefA will be saved into MTP automatically by CoolFlux */
    /* cold boot, need to load all parameters and patches */
    coldStartup(g_handle, mSpeakerSampleRate);

    /*Set to calibration once*/
    setOtc(g_handle, 1);

    err = Tfa9887_ReadRegister16(g_handle, TFA9887_MTP, &mtp);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("MTP = 0x%x\n", mtp);

    loadSpeakerFile(LOCATION_FILES SPEAKER_FILENAME, loadedSpeaker);
    Tfa9887_SelectAmplifierInput(g_handle, Tfa9887_AmpInputSel_I2SLeft);

    /* Check if MTPEX bit is set for calibration once mode
    /* Calibration always would always do the complete 2 step calibration*/
    if (checkMTPEX(g_handle) == 0)
    {
        ALOGD("checkMTPEX(handle) == 0");
        /* ensure no audio during special calibration */
        err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Digital);
        assert(err == Tfa9887_Error_Ok);

        ALOGD("still tCoef in speaker file, special calibration needed\n");
        err = calculateSpeakertCoefA(g_handle, loadedSpeaker);
        assert(err == Tfa9887_Error_Ok);

        resetMtpEx(g_handle);

        /* force recalibration now with correct tCoefA */
        ALOGD(" 1 muteAmplifier");
        muteAmplifier(g_handle); /* clean shutdown to avoid plop */
        ALOGD(" 2 coldStartup");
        coldStartup(g_handle, mSpeakerSampleRate);
        ALOGD("-checkMTPEX(handle) == 0");
    }
    else
    {
        ALOGD("DSP already calibrated. Calibration skipped and previous calibration results loaded from MTP.\n");
    }

    load_all_settings(g_handle, loadedSpeaker, LOCATION_FILES CONFIG_FILENAME, LOCATION_FILES PRESET_FILENAME, LOCATION_FILES EQ_FILENAME);

    /* do calibration (again), if needed */
    ALOGD("Tfa9887_SetConfigured ");
    err = Tfa9887_SetConfigured(g_handle);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("waitCalibration ");
    waitCalibration(g_handle, &calibrateDone);
    if (calibrateDone)
    {
        ALOGD("Tfa9887_DspGetCalibrationImpedance ");
        Tfa9887_DspGetCalibrationImpedance(g_handle, &re25);
    }
    else
    {
        ALOGD("Calibration is not done");
        re25 = 0;
    }
    ALOGD("Calibration value is %2.2f ohm\n", re25);

    /*Checking the current status for DSP status and DCPVP */
    ALOGD("statusCheck ");
    statusCheck(g_handle);

    ALOGD("Tfa9887_SetMute ");
    err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Digital);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("Tfa9887_GetMute ");
    err = Tfa9887_GetMute(g_handle, &mute);
    assert(err == Tfa9887_Error_Ok);

    assert(mute == Tfa9887_Mute_Digital);

    for (i = 5; i >= 0; i--)
    {
        ALOGD("Setting volume to %3.1f dB\n", -6.0f * i);
        err = Tfa9887_SetVolume(g_handle, -6.0f * i);
        assert(err == Tfa9887_Error_Ok);
        dump_state_info(&stateInfo);
        usleep(1 * 1000);
    }
    ALOGD("return");
    return 1;

}

int tfa9887_deinit(void)
{
    ALOGD("tfa9887_deinit");
    Tfa9887_Error_t err = Tfa9887_Error_Other;
    /* check LS model */
    ALOGD("1 Tfa9887_DspReadSpeakerParameters ");
    err = Tfa9887_DspReadSpeakerParameters(g_handle, lsModel);
    assert(err == Tfa9887_Error_Ok);
    /*Remark: tCoefA value could be get by using the function below to verify the tCoefA value*/
    ALOGD("2 tCoefFromSpeaker ");
    tCoefA = tCoefFromSpeaker(lsModel);
    ALOGD("3 Tfa9887_SetMute ");
    err = Tfa9887_SetMute(g_handle, Tfa9887_Mute_Amplifier);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("4 Tfa9887_Powerdown ");
    err = Tfa9887_Powerdown(g_handle, 1);
    assert(err == Tfa9887_Error_Ok);
    ALOGD("5 Tfa9887_Close ");
    err = Tfa9887_Close(g_handle);
    g_handle = 0;
    assert(err == Tfa9887_Error_Ok);
    return err;
}

void tfa9887_SpeakerOn(void)
{
    ALOGD("+tfa9887_SpeakerOn");
    int i = 0;
    if (tfa9887_check_tfaopen() == 0)
    {
        tfa9887_init();
        // Sleep to wait for DSP stabled
        usleep(5 * 1000);
    }
    Tfa98xx_Error_t err = Tfa98xx_Error_Ok;
    Tfa98xx_handle_t handle = g_handle;

    if (err != Tfa98xx_Error_Ok)
    {
        ALOGD("Tfa98xx_Powerdown to 0 error(%d)", err);
    }

    err = Tfa98xx_SetMute(handle, Tfa98xx_Mute_Off);
    if (err != Tfa98xx_Error_Ok)
    {
        ALOGD("Tfa98xx_SetMute to Tfa98xx_Mute_Off error(%d)", err);
        return;
    }
    // Sleep to wait for DSP stabled
    usleep(5 * 1000);

    MtkTfa98xxBypassOn();
    err = Tfa98xx_Powerdown(g_handle, 0);

    // Sleep to wait for DSP stabled
    usleep(5 * 1000);

    ALOGD("-tfa9887_SpeakerOn");
}

void tfa9887_SpeakerOff(void)
{
    Tfa98xx_Error_t err = Tfa98xx_Error_Ok;
    Tfa98xx_handle_t handle = g_handle;

    err = Tfa98xx_SetMute(handle, Tfa98xx_Mute_Digital);
    if (err != Tfa98xx_Error_Ok)
    {
        ALOGD("Tfa98xx_SetMute to Tfa98xx_Mute_Digital error(%d)", err);
        return;
    }
    err = Tfa98xx_Powerdown(handle, 1);
    usleep(15 * 1000);
    if (err != Tfa98xx_Error_Ok)
    {
        ALOGD("Tfa98xx_Powerdown to 1 error(%d)", err);
        return;
    }
    ALOGD("-");
}

void tfa9887_reset(void)
{
    tfa9887_deinit();
    g_handle = 0;
}

void tfa9887_setSamplerate(int samplerate)
{
    ALOGD("tfa9887_setSamplerate samplerate = %d", samplerate);
    mSpeakerSampleRate = samplerate;
}

void tfa9887_set_bypass_dsp_incall(int bypass)
{
    ALOGD("+tfa9887_set_bypass_dsp_incall bypass", bypass);
    bypass_dsp = bypass == 0 ? 0 : 1;
    ALOGD("-tfa9887_set_bypass_dsp_incall bypass_dsp=%d", bypass_dsp);
}

void tfa9887_EchoReferenceConfigure(int config)
{
    ALOGD("tfa9887_EchoReferenceConfigure ");
    Tfa98xx_Error_t err = Tfa98xx_Error_Ok;
    Tfa98xx_handle_t handle = g_handle;
    if (config)
    {
        Tfa98xx_SelectI2SOutputLeft(handle, Tfa98xx_I2SOutputSel_DSP_AEC);
        ALOGD("tfa9890_EchoReferenceConfigure Left, error(%d)", err);
        assert(err == Tfa98xx_Error_Ok);

        Tfa98xx_SelectI2SOutputRight(handle, Tfa98xx_I2SOutputSel_DSP_AEC);
        ALOGD("tfa9890_EchoReferenceConfigure Right, error(%d)", err);
        assert(err == Tfa98xx_Error_Ok);
    }
    ALOGD("%s -, flag= %d", __func__, config);
}

